"""Shared Streamlit helpers: cached artifact loading, colors, status, errors."""

import json
import sys
from pathlib import Path

import pandas as pd
import plotly.express as px
import streamlit as st

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from src.config import (  # noqa: E402
    MODEL_METADATA_PATH,
    OUTPUTS_DIR,
    SEGMENT_MAPPING_PATH,
)
from src.inference import load_artifacts  # noqa: E402

TRAIN_HINT = "Run the training pipeline first:  python -m src.pipeline"

# One deterministic color per cluster id, reused on every page.
SEGMENT_COLOR_SEQUENCE = px.colors.qualitative.Bold


def segment_colors(mapping: dict) -> dict[str, str]:
    """Deterministic segment-name -> color map keyed by cluster id."""
    return {
        name: SEGMENT_COLOR_SEQUENCE[int(cid) % len(SEGMENT_COLOR_SEQUENCE)]
        for cid, name in sorted(mapping["segments"].items(), key=lambda kv: int(kv[0]))
    }


@st.cache_resource(show_spinner=False)
def get_model_artifacts():
    """Persisted scaler/model/mapping/schema. Never retrains."""
    return load_artifacts()


@st.cache_data(show_spinner=False)
def load_json_output(name: str) -> dict | list:
    path = OUTPUTS_DIR / name
    if not path.exists():
        raise FileNotFoundError(name)
    return json.loads(path.read_text())


@st.cache_data(show_spinner=False)
def load_csv_output(name: str, **kwargs) -> pd.DataFrame:
    path = OUTPUTS_DIR / name
    if not path.exists():
        raise FileNotFoundError(name)
    return pd.read_csv(path, **kwargs)


@st.cache_data(show_spinner=False)
def load_segments_table() -> pd.DataFrame:
    path = OUTPUTS_DIR / "customer_segments.parquet"
    if not path.exists():
        raise FileNotFoundError("customer_segments.parquet")
    return pd.read_parquet(path)


@st.cache_data(show_spinner=False)
def load_metadata() -> dict:
    if not MODEL_METADATA_PATH.exists():
        raise FileNotFoundError("model_metadata.json")
    return json.loads(MODEL_METADATA_PATH.read_text())


@st.cache_data(show_spinner=False)
def load_segment_mapping() -> dict:
    if not SEGMENT_MAPPING_PATH.exists():
        raise FileNotFoundError("segment_mapping.json")
    return json.loads(SEGMENT_MAPPING_PATH.read_text())


def require_outputs(loader, *args):
    """Load an artifact or stop the page with a friendly message."""
    try:
        return loader(*args)
    except FileNotFoundError as exc:
        st.error(f"Required generated artifact is missing ({exc}). {TRAIN_HINT}")
        st.stop()
    except (ValueError, KeyError, json.JSONDecodeError):
        st.error(f"A generated artifact appears corrupted or outdated. {TRAIN_HINT}")
        st.stop()


def compatibility_problems(metadata: dict, schema: dict) -> list[str]:
    """Model/schema version and feature-contract mismatch detection."""
    problems = []
    if metadata.get("feature_schema_version") != schema.get("schema_version"):
        problems.append(
            "Feature schema version mismatch between model metadata "
            f"({metadata.get('feature_schema_version')}) and schema "
            f"({schema.get('schema_version')})."
        )
    schema_names = [
        f["name"] for f in sorted(schema.get("features", []), key=lambda f: f["order"])
    ]
    if metadata.get("features") != schema_names:
        problems.append(
            f"Feature list mismatch: metadata {metadata.get('features')} vs "
            f"schema {schema_names}."
        )
    return problems


def render_sidebar_status() -> None:
    """Compact global model status in the sidebar (actual values only)."""
    st.sidebar.markdown("---")
    st.sidebar.markdown("**Model status**")
    try:
        meta = load_metadata()
        st.sidebar.caption(
            f"K-Means · K={meta['selected_k']} · {meta.get('model_version', 'n/a')}"
        )
        st.sidebar.caption("Features: " + ", ".join(meta.get("features", [])))
        st.sidebar.caption(f"Trained: {meta.get('trained_at_utc', 'n/a')}")
        st.sidebar.caption("Status: Loaded")
    except FileNotFoundError:
        st.sidebar.warning("Model not trained yet. Run: python -m src.pipeline")


def artifact_caption() -> None:
    st.caption(
        "All metrics on this page are loaded from artifacts generated by "
        "`python -m src.pipeline` — nothing is hard-coded or recomputed live. "
        "The dashboard runs from derived outputs; the raw dataset is not required."
    )
