"""Customer Segmentation and Retail Intelligence — Streamlit application.

Run with:  streamlit run app/predict.py

Loads persisted model artifacts and derived analytical outputs generated by
`python -m src.pipeline`. Never retrains or refits anything at runtime.
"""

import sys
from pathlib import Path

import pandas as pd
import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app import charts  # noqa: E402
from app.components import (  # noqa: E402
    TRAIN_HINT,
    artifact_caption,
    compatibility_problems,
    get_model_artifacts,
    load_csv_output,
    load_json_output,
    load_metadata,
    load_segment_mapping,
    load_segments_table,
    render_sidebar_status,
    require_outputs,
    segment_colors,
)
from src.inference import assign_segment  # noqa: E402

st.set_page_config(
    page_title="Customer Segmentation & Retail Intelligence",
    page_icon="📊",
    layout="wide",
)

PAGES = [
    "Executive Overview",
    "Customer Segments",
    "Model Analysis",
    "Customer Behavior",
    "Segment Predictor",
    "Business Insights",
    "Data & Methodology",
]

st.sidebar.title("Retail Intelligence")
page = st.sidebar.radio("Navigate", PAGES)
render_sidebar_status()
st.sidebar.caption(
    "Customer Segmentation and Retail Intelligence · UCI Online Retail · "
    "RFM + K-Means · Streamlit"
)


def _fmt_money(value: float) -> str:
    return f"£{value:,.0f}"


# Startup compatibility check (artifact versions must match).
try:
    _meta = load_metadata()
    _scaler, _model, _mapping, _schema = get_model_artifacts()
    _problems = compatibility_problems(_meta, _schema)
    if _problems:
        st.error(
            "Incompatible model artifacts detected — retrain before using the "
            "dashboard:\n\n- " + "\n- ".join(_problems) + f"\n\n{TRAIN_HINT}"
        )
        st.stop()
except FileNotFoundError:
    pass  # individual pages show the friendly missing-artifact message
except ValueError as exc:
    st.error(f"Model/schema incompatibility: {exc}")
    st.stop()

# ----------------------------------------------------------------- overview
if page == "Executive Overview":
    st.title("Executive Overview")
    artifact_caption()
    summary = require_outputs(load_json_output, "summary.json")
    segments = require_outputs(load_segments_table)
    mapping = require_outputs(load_segment_mapping)
    profiles = require_outputs(load_csv_output, "segment_profiles.csv")
    colors = segment_colors(mapping)

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Customers", f"{summary['total_customers']:,}")
    c2.metric("Valid orders", f"{summary['valid_orders']:,}")
    c3.metric("Total revenue", _fmt_money(summary["total_revenue"]))
    c4.metric("Avg order value", _fmt_money(summary["avg_order_value"]))

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Segments (K)", summary["selected_k"])
    c2.metric("Silhouette score", f"{summary['silhouette']:.4f}")
    c3.metric("Observation start", summary["observation_start"])
    c4.metric("Observation end", summary["observation_end"])

    col1, col2 = st.columns(2)
    with col1:
        st.plotly_chart(charts.segment_distribution(segments, colors), width="stretch")
    with col2:
        st.plotly_chart(charts.revenue_by_segment(profiles, colors), width="stretch")

    st.plotly_chart(charts.share_comparison(profiles), width="stretch")

    monthly = require_outputs(load_csv_output, "monthly_activity.csv")
    col1, col2 = st.columns(2)
    with col1:
        st.plotly_chart(
            charts.monthly_trend(monthly, "orders", "Valid orders per month"),
            width="stretch",
        )
    with col2:
        st.plotly_chart(
            charts.monthly_trend(monthly, "revenue", "Revenue per month (£)"),
            width="stretch",
        )

    country = require_outputs(load_csv_output, "country_summary.csv")
    metric = st.radio(
        "Geography metric",
        ["Customers", "Revenue"],
        horizontal=True,
        help="Both metrics are computed from valid purchase transactions.",
    )
    value_col = "customers" if metric == "Customers" else "revenue"
    st.plotly_chart(
        charts.country_bar(country, value_col, f"{metric} by country (top 12)"),
        width="stretch",
    )

# ----------------------------------------------------------------- segments
elif page == "Customer Segments":
    st.title("Customer Segments")
    artifact_caption()
    mapping = require_outputs(load_segment_mapping)
    segments = require_outputs(load_segments_table)
    comparison = require_outputs(load_csv_output, "population_comparison.csv")
    colors = segment_colors(mapping)

    names = mapping["segments"]
    choice = st.selectbox(
        "Select a segment",
        list(names.values()),
        help="Segment names are derived from each cluster's actual median RFM profile.",
    )
    cid = next(int(k) for k, v in names.items() if v == choice)
    profile = next(p for p in mapping["profiles"] if p["cluster"] == cid)
    subset = segments[segments["cluster"] == cid]

    st.subheader(f"Cluster {cid}: {choice}")
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Customers", f"{profile['count']:,}")
    c2.metric("Customer share", f"{profile['share_pct']}%")
    c3.metric("Segment revenue", _fmt_money(profile["revenue"]))
    c4.metric("Revenue share", f"{profile['revenue_share_pct']}%")

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Median recency", f"{profile['median_Recency']:.0f} days")
    c2.metric("Median orders", f"{profile['median_Frequency']:.0f}")
    c3.metric("Median spend", _fmt_money(profile["median_Monetary"]))
    c4.metric("Median AOV", _fmt_money(profile["median_AvgOrderValue"]))

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Median products", f"{profile['median_UniqueProducts']:.0f}")
    c2.metric("Median active days", f"{profile['median_ActiveDays']:.0f}")
    c3.metric("Mean spend", _fmt_money(profile["mean_Monetary"]))
    c4.metric("Mean orders", f"{profile['mean_Frequency']:.1f}")

    st.plotly_chart(charts.profile_heatmap(comparison, mapping), width="stretch")

    st.subheader("Country distribution within this segment")
    seg_revenue = float(subset["Monetary"].sum())
    country_table = (
        subset.groupby("Country", observed=True)
        .agg(Customers=("CustomerID", "count"), Revenue=("Monetary", "sum"))
        .reset_index()
        .sort_values("Customers", ascending=False)
        .head(10)
    )
    country_table["% of Segment"] = (100 * country_table["Customers"] / len(subset)).round(1)
    country_table["% of Segment Revenue"] = (
        100 * country_table["Revenue"] / seg_revenue
    ).round(1)
    country_table["Revenue"] = country_table["Revenue"].round(0)
    st.dataframe(country_table, width="stretch", hide_index=True)

# ------------------------------------------------------------ model analysis
elif page == "Model Analysis":
    st.title("Model Analysis")
    artifact_caption()
    evaluation = require_outputs(load_csv_output, "model_evaluation.csv")
    metadata = require_outputs(load_metadata)
    mapping = require_outputs(load_segment_mapping)
    segments = require_outputs(load_segments_table)
    comparison = require_outputs(load_csv_output, "population_comparison.csv")
    profiles = require_outputs(load_csv_output, "segment_profiles.csv")
    colors = segment_colors(mapping)
    selected_k = metadata["selected_k"]

    col1, col2 = st.columns(2)
    with col1:
        st.plotly_chart(charts.elbow_curve(evaluation, selected_k), width="stretch")
    with col2:
        st.plotly_chart(charts.silhouette_bars(evaluation, selected_k), width="stretch")

    st.subheader("Why this K?")
    st.info(metadata["k_selection"]["explanation"])
    with st.expander("Deterministic K-selection procedure"):
        st.markdown(metadata["k_selection"]["procedure"])
        st.json(metadata["k_selection"]["parameters"])

    st.subheader("Candidate K decision table")
    st.dataframe(evaluation.round(4), width="stretch", hide_index=True)
    st.caption(
        "Every candidate K, including K=2, is shown — nothing is hidden. "
        f"Fixed seed set {metadata['stability_seeds']} was used for every K; "
        f"ARI is measured versus the deterministic "
        f"seed-{metadata['stability_reference_seed']} "
        "reference run (a reference, not ground truth)."
    )

    st.subheader("Seed stability")
    st.dataframe(
        evaluation[["k", "sil_mean_seeds", "sil_std_seeds", "ari_mean_vs_seed42"]].round(4),
        width="stretch",
        hide_index=True,
    )

    col1, col2 = st.columns(2)
    with col1:
        st.plotly_chart(charts.cluster_size(profiles, colors), width="stretch")
    with col2:
        st.plotly_chart(charts.profile_heatmap(comparison, mapping), width="stretch")

    st.subheader("PCA cluster visualization")
    st.caption(
        "PCA is used only to visualize the customer clusters in two dimensions. "
        "K-Means is trained on the full modeling feature space "
        f"({', '.join(metadata['features'])}, log1p + StandardScaler). "
        f"Explained variance ratio: {metadata['pca_explained_variance_ratio']}."
    )
    st.plotly_chart(charts.pca_scatter(segments, colors), width="stretch")

    st.subheader("Model configuration")
    config_rows = {
        "Algorithm": metadata["algorithm"],
        "Selected K": metadata["selected_k"],
        "Features": ", ".join(metadata["features"]),
        "Transformation": metadata["transformation"],
        "Scaler": metadata["scaler"],
        "random_state": metadata["random_state"],
        "n_init": metadata["n_init"],
        "Final inertia": round(metadata["validation"]["inertia"], 1),
        "Final silhouette": round(metadata["validation"]["silhouette"], 4),
        "Model version": metadata["model_version"],
        "Feature schema version": metadata["feature_schema_version"],
        "Trained (UTC)": metadata["trained_at_utc"],
        "scikit-learn": metadata["scikit_learn_version"],
    }
    st.table(
        pd.DataFrame(
            [(k, str(v)) for k, v in config_rows.items()],
            columns=["Setting", "Value"],
        )
    )

# --------------------------------------------------------- customer behavior
elif page == "Customer Behavior":
    st.title("Customer Behavior")
    artifact_caption()
    segments = require_outputs(load_segments_table)
    mapping = require_outputs(load_segment_mapping)
    colors = segment_colors(mapping)

    selected = st.multiselect(
        "Segments",
        sorted(segments["segment"].unique()),
        default=sorted(segments["segment"].unique()),
    )
    countries = st.multiselect(
        "Countries (optional filter)", sorted(segments["Country"].unique())
    )
    view = segments[segments["segment"].isin(selected)] if selected else segments
    if countries:
        view = view[view["Country"].isin(countries)]
    if view.empty:
        st.warning("No customers match the current filters.")
        st.stop()
    st.caption(f"{len(view):,} customers in view")

    feature = st.selectbox(
        "Behavioural feature",
        [
            "Recency",
            "Frequency",
            "Monetary",
            "AvgOrderValue",
            "UniqueProducts",
            "TotalQuantity",
            "ActiveDays",
        ],
    )
    log_scale = st.checkbox(
        "Log scale (recommended for skewed monetary features)",
        value=feature in {"Monetary", "AvgOrderValue", "TotalQuantity"},
    )
    if log_scale and float(view[feature].min()) <= 0:
        st.info(
            f"{feature} contains zero values, so a log axis is not applicable; "
            "showing a linear scale."
        )
        log_scale = False
    col1, col2 = st.columns(2)
    with col1:
        st.plotly_chart(
            charts.feature_histogram(view, feature, log_scale, colors), width="stretch"
        )
    with col2:
        st.plotly_chart(
            charts.feature_box_by_segment(view, feature, log_scale, colors),
            width="stretch",
        )

    st.subheader("Scatter exploration")
    axes = ["Recency", "Frequency", "Monetary"]
    c1, c2, c3, c4 = st.columns(4)
    x_axis = c1.selectbox("X axis", axes, index=0)
    y_axis = c2.selectbox("Y axis", axes, index=2)
    log_x = c3.checkbox("Log X", value=False)
    log_y = c4.checkbox("Log Y", value=(y_axis == "Monetary"))
    if log_x and float(view[x_axis].min()) <= 0:
        st.info(f"{x_axis} contains zero values; using a linear X axis.")
        log_x = False
    if log_y and float(view[y_axis].min()) <= 0:
        st.info(f"{y_axis} contains zero values; using a linear Y axis.")
        log_y = False
    st.plotly_chart(
        charts.scatter_explore(view, x_axis, y_axis, colors, log_x, log_y),
        width="stretch",
    )

# ------------------------------------------------------------------ predictor
elif page == "Segment Predictor":
    st.title("Customer Segment Predictor")
    st.markdown(
        "This tool assigns an **already-computed customer behavioral profile** "
        "to the trained segmentation model. RFM features require transaction "
        "history — this tool does not derive them from demographics."
    )
    with st.expander("Feature definitions (must match training)"):
        st.markdown(
            "- **Recency** — days since the customer's most recent valid purchase (≥ 0)\n"
            "- **Frequency** — number of unique valid purchase orders (≥ 1)\n"
            "- **Monetary** — total valid purchase revenue for the customer (> 0)\n\n"
            "The saved log1p transform, StandardScaler, and K-Means model are "
            "applied exactly as during training. Nothing is retrained."
        )
    try:
        scaler, model, mapping, schema = get_model_artifacts()
    except FileNotFoundError:
        st.error(f"Required model artifacts are missing. {TRAIN_HINT}")
        st.stop()
    except ValueError as exc:
        st.error(f"Model/schema incompatibility: {exc}")
        st.stop()

    with st.form("predictor"):
        c1, c2, c3 = st.columns(3)
        recency = c1.number_input(
            "Recency (days)",
            min_value=0.0,
            max_value=100000.0,
            value=30.0,
            help="Days since the most recent valid purchase.",
        )
        frequency = c2.number_input(
            "Frequency (orders)",
            min_value=1.0,
            max_value=100000.0,
            value=5.0,
            help="Unique valid purchase invoices.",
        )
        monetary = c3.number_input(
            "Monetary (total revenue, £)",
            min_value=0.01,
            value=1500.0,
            help="Total valid purchase revenue.",
        )
        submitted = st.form_submit_button("Assign segment", type="primary")

    if submitted:
        inputs = {"Recency": recency, "Frequency": frequency, "Monetary": monetary}
        try:
            result = assign_segment(
                inputs, scaler=scaler, model=model, mapping=mapping, schema=schema
            )
        except ValueError as exc:
            st.error(f"Invalid input: {exc}")
            st.stop()
        for warning in result["warnings"]:
            st.warning(warning)
        st.success(
            f"Assigned Segment — Cluster {result['cluster']}: " f"**{result['segment_name']}**"
        )
        st.caption(
            "K-Means assigns the nearest learned centroid; this is a segment "
            "assignment, not a calibrated prediction confidence."
        )
        st.markdown("**Input summary**")
        st.table(
            pd.DataFrame(
                {"Feature": list(inputs), "Value": [f"{v:g}" for v in inputs.values()]}
            )
        )
        profile = result["profile"]
        if profile:
            c1, c2, c3, c4 = st.columns(4)
            c1.metric("Segment size", f"{profile['count']:,}")
            c2.metric("Customer share", f"{profile['share_pct']}%")
            c3.metric("Median spend", _fmt_money(profile["median_Monetary"]))
            c4.metric("Revenue share", f"{profile.get('revenue_share_pct', 'n/a')}%")

# ------------------------------------------------------------------ insights
elif page == "Business Insights":
    st.title("Business Insights")
    artifact_caption()
    st.warning(
        "These insights are observational hypotheses derived from clustering "
        "results. They do not establish that any strategy will cause revenue, "
        "retention, or loyalty changes; proposed strategies should be validated "
        "through controlled experiments."
    )
    insights = require_outputs(load_json_output, "business_insights.json")
    mapping = require_outputs(load_segment_mapping)
    profiles = require_outputs(load_csv_output, "segment_profiles.csv")
    colors = segment_colors(mapping)

    st.plotly_chart(charts.share_comparison(profiles), width="stretch")

    for item in insights:
        with st.expander(f"Cluster {item['cluster']} — {item['segment']}", expanded=True):
            c1, c2 = st.columns(2)
            c1.metric("Customer share", f"{item['customer_share_pct']}%")
            c2.metric("Revenue share", f"{item['revenue_share_pct']}%")
            st.markdown(f"**Observed profile:** {item['observed_profile']}")
            st.markdown(f"**Potential strategy to test:** {item['potential_strategy']}")
            st.markdown(f"**Risk / opportunity:** {item['risk_or_opportunity']}")
            st.caption(item["caution"])

# --------------------------------------------------------------- methodology
else:
    st.title("Data & Methodology")
    summary = require_outputs(load_json_output, "summary.json")
    counts = summary["cleaning_counts"]

    st.subheader("Pipeline")
    st.code(
        "UCI Online Retail\n"
        "      ↓\nData Validation\n      ↓\nTransaction Cleaning\n"
        "      ↓\nValid Transactions (unique InvoiceNo)\n"
        "      ↓\nCustomer Aggregation\n      ↓\nRFM + Behavioral Features\n"
        "      ↓\nFeature Selection (redundancy analysis)\n"
        "      ↓\nlog1p Transformation\n      ↓\nStandardScaler\n"
        "      ↓\nK-Means Candidate Evaluation (K=2..8)\n"
        "      ↓\nFixed-Seed Stability + Deterministic K Selection\n"
        "      ↓\nFinal K-Means\n      ↓\nCluster Profiling\n"
        "      ↓\nBusiness Interpretation\n      ↓\nPersisted Model\n"
        "      ↓\nInference\n      ↓\nStreamlit Retail Intelligence",
        language=None,
    )

    with st.expander("What is RFM?", expanded=False):
        st.markdown(
            "- **Recency** — how recently a customer purchased.\n"
            "- **Frequency** — how many unique valid orders a customer made.\n"
            "- **Monetary** — how much valid revenue a customer generated.\n\n"
            "Together they provide three complementary dimensions of "
            "purchasing behavior."
        )

    st.markdown(f"""
### Dataset
**UCI Online Retail** (dataset id 352) — transaction-level records from a
UK-based online retailer, {summary['observation_start']} to
{summary['observation_end']}. Source:
[archive.ics.uci.edu/dataset/352/online+retail](https://archive.ics.uci.edu/dataset/352/online+retail)
(CC BY 4.0). The raw file is **not** committed to the repository; this
dashboard reads derived, reproducible artifacts from `outputs/`.

### Cleaning policy (counts from the actual run)
| Step | Rows |
|---|---|
| Rows loaded | {counts['rows_loaded']:,} |
| Exact duplicate rows removed | {counts['duplicate_rows_removed']:,} |
| Missing CustomerID removed | {counts['missing_customer_id_removed']:,} |
| Invalid dates removed | {counts['invalid_date_removed']:,} |
| Cancellation invoices removed ("C" prefix) | {counts['cancellation_rows_removed']:,} |
| Non-positive quantity/price removed | {counts['non_positive_qty_or_price_removed']:,} |
| **Valid rows retained** | **{counts['valid_rows']:,}** |

### Transaction definition
One **order** = one unique valid `InvoiceNo` after cleaning. Multiple product
rows on one invoice count as one order. This definition is used consistently
for Frequency, AOV, recency, and every dashboard metric.

### Reference date & observation period
`reference_date = max(valid InvoiceDate) + 1 day = {summary['reference_date']}` —
deterministic, so Recency never changes between reruns and no future
information leaks into features.

### Features
RFM computed per customer from valid purchases only. Additional behavioural
features (AvgOrderValue, UniqueProducts, TotalQuantity, ActiveDays, Country)
are computed for profiling and this dashboard but are **not** model inputs:
Spearman correlation analysis (see `outputs/correlation_matrix.csv`) showed
they are heavily redundant with RFM, and feature-set sweeps lowered
silhouette at every K. CustomerID is never a feature.

### Modelling and K selection
log1p transform → StandardScaler → K-Means (random_state=42, n_init=10).
K=2..8 evaluated with inertia, silhouette, cluster-size balance, and
fixed-seed stability; the final K={summary['selected_k']} is the output of a
deterministic multi-criteria procedure (quantitative leader:
K={summary['quantitative_best_k']}). {summary['k_selection_reason']}

### Limitations
Single retailer, single year (retrospective snapshot); K-Means assumes
roughly spherical clusters in the scaled space and yields hard assignments;
silhouette {summary['silhouette']:.4f} indicates moderate, not sharp,
separation — typical for continuous behavioural data. The dataset does not
provide a validated future churn outcome; therefore the segmentation is
evaluated primarily using internal clustering diagnostics and descriptive
behavioral differences. Business recommendations are hypotheses that require
controlled experiments; external inference is only as reliable as the
supplied behavioral features.
""")
